### ISSUE TITLE
Can't get it to run on MacOS

### ISSUE THREAD

**Issue by jmichas** [michaelgale/cq-gridfinity#15]
I have been trying to get everything running for a while but I keep getting module not found errors for OCC and OCP depending on what import I try - cadquery, cqkit or cqgridfinity. 

I installed cqgridfinity using pipx and I am running in my cqgridfinity venv. 
What am I doing wrong?

Here are my packages as listed from pip:
python3 -m pip list                 
Package                       Version
----------------------------- --------------
aiohappyeyeballs              2.4.4
aiohttp                       3.11.11
aiosignal                     1.3.2
alabaster                     1.0.0
applaunchservices             0.3.0
appnope                       0.1.4
arrow                         1.3.0
astroid                       3.3.6
asttokens                     3.0.0
asyncssh                      2.19.0
atomicwrites                  1.4.1
attrs                         24.3.0
autopep8                      2.0.4
babel                         2.16.0
beautifulsoup4                4.12.3
binaryornot                   0.4.4
black                         24.10.0
bleach                        6.2.0
cadquery                      2.3.0
certifi                       2024.12.14
cffi                          1.17.1
chardet                       5.2.0
charset-normalizer            3.4.0
click                         8.1.7
cloudpickle                   3.1.0
cmake                         3.31.2
comm                          0.2.2
cookiecutter                  2.6.0
CQ-editor                     0.3.0.dev0
cqgridfinity                  0.5.7
cqkit                         0.5.8
cryptography                  44.0.0
debugpy                       1.8.11
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.15
diff-match-patch              20241021
dill                          0.3.9
docstring-to-markdown         0.15
docutils                      0.21.2
executing                     2.1.0
fastjsonschema                2.21.1
flake8                        7.1.1
frozenlist                    1.5.0
idna                          3.10
imagesize                     1.4.1
importlib_metadata            8.5.0
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.29.5
ipython                       8.30.0
isort                         5.13.2
jaraco.classes                3.4.0
jaraco.context                6.0.1
jaraco.functools              4.1.0
jedi                          0.19.2
jellyfish                     1.1.3
Jinja2                        3.1.4
jsonschema                    4.23.0
jsonschema-specifications     2024.10.1
jupyter_client                8.6.3
jupyter_core                  5.7.2
jupyterlab_pygments           0.3.0
keyring                       25.5.0
Logbook                       1.8.0
markdown-it-py                3.0.0
MarkupSafe                    3.0.2
matplotlib-inline             0.1.7
mccabe                        0.7.0
mdurl                         0.1.2
mistune                       3.0.2
more-itertools                10.5.0
multidict                     6.1.0
mypy-extensions               1.0.0
nbclient                      0.10.2
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
numpy                         2.2.0
numpydoc                      1.8.0
OCP-stubs                     7.7.0
packaging                     24.2
pandocfilters                 1.5.1
parso                         0.8.4
pathspec                      0.12.1
pexpect                       4.9.0
pickleshare                   0.7.5
pip                           24.3.1
platformdirs                  4.3.6
pluggy                        1.5.0
prompt_toolkit                3.0.48
propcache                     0.2.1
psutil                        6.1.1
ptyprocess                    0.7.0
pure_eval                     0.2.3
pycodestyle                   2.12.1
pycparser                     2.22
pydocstyle                    6.3.0
pyflakes                      3.2.0
PyGithub                      2.5.0
Pygments                      2.18.0
PyJWT                         2.10.1
pylint                        3.3.2
pylint-venv                   3.0.4
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyobjc-core                   10.3.2
pyobjc-framework-Cocoa        10.3.2
pyobjc-framework-CoreServices 10.3.2
pyobjc-framework-FSEvents     10.3.2
PyQt5                         5.15.11
PyQt5-Qt5                     5.15.16
PyQt5_sip                     12.16.1
pyqtgraph                     0.13.7
PyQtWebEngine                 5.15.7
PyQtWebEngine-Qt5             5.15.16
python-dateutil               2.9.0.post0
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.12.0
python-slugify                8.0.4
pytoolconfig                  1.3.1
pyuca                         1.2
PyYAML                        6.0.2
pyzmq                         26.2.0
QDarkStyle                    3.2.3
qstylizer                     0.2.4
QtAwesome                     1.3.1
qtconsole                     5.6.1
QtPy                          2.4.2
referencing                   0.35.1
requests                      2.32.3
rich                          13.9.4
rope                          1.13.0
rpds-py                       0.22.3
Rtree                         1.3.0
setuptools                    75.6.0
six                           1.17.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.6
Sphinx                        8.1.3
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
spyder                        6.0.3
spyder-kernels                3.0.2
stack-data                    0.6.3
superqt                       0.7.0
tabulate                      0.9.0
text-unidecode                1.3
textdistance                  4.6.3
three-merge                   0.1.1
tinycss2                      1.4.0
tomlkit                       0.13.2
tornado                       6.4.2
traitlets                     5.14.3
types-python-dateutil         2.9.0.20241206
typing_extensions             4.12.2
ujson                         5.10.0
urllib3                       2.2.3
watchdog                      6.0.0
wcwidth                       0.2.13
webencodings                  0.5.1
whatthepatch                  1.0.7
wrapt                         1.17.0
wurlitzer                     3.1.1
yapf                          0.43.0
yarl                          1.18.3
zipp                          3.21.0

**Comment by jmichas** [comment]
Ok, I gave it another shot using based on some info from another issue I had read where there was an assumption that cq-editor would be installed first. I deleted my previous venv and installed cq-editor, then I activated that as my venv and used pip to install cqgridfinity and voila, it worked. This should be in the docs for those of us who are not coming from a python code 3d world, I'm from the Fusion 360 world and only found this project via a Makerworld post that linked to cqgridfinity. This will make it so much easier to generate baseplates for various sized drawers and containers it is pretty amazing.

**Comment by michaelgale** [comment]
Glad you got it working.  The tricky thing is getting a reliable installation of CadQuery working because of its binary dependancies to the OpenCascade CAD kernel.  The CQ team have been making good progress in making more robust installation packages for conda, etc. to help folks with a more "turn-key" setup experience.
